<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Tenant;
use App\Models\Township;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    private array $locations = [
        [
            'name' => 'Yangon',
            'delivery_fee' => 2000,
            'townships' => [
                ['name' => 'Hlaing', 'postal_code' => '11051'],
                ['name' => 'Sanchaung', 'postal_code' => '11111'],
                ['name' => 'Kamayut', 'postal_code' => '11041'],
                ['name' => 'Bahan', 'postal_code' => '11201'],
                ['name' => 'Dagon', 'postal_code' => '11131'],
                ['name' => 'Kyauktada', 'postal_code' => '11181'],
                ['name' => 'Latha', 'postal_code' => '11131'],
                ['name' => 'Pabedan', 'postal_code' => '11141'],
                ['name' => 'Botataung', 'postal_code' => '11161'],
                ['name' => 'Pazundaung', 'postal_code' => '11171'],
                ['name' => 'Yankin', 'postal_code' => '11081'],
                ['name' => 'Tamwe', 'postal_code' => '11211'],
                ['name' => 'Thingangyun', 'postal_code' => '11071'],
                ['name' => 'South Okkalapa', 'postal_code' => '11091'],
                ['name' => 'North Okkalapa', 'postal_code' => '11081'],
                ['name' => 'Mayangon', 'postal_code' => '11061'],
                ['name' => 'Insein', 'postal_code' => '11051'],
                ['name' => 'Hlaingthaya', 'postal_code' => '11401'],
                ['name' => 'Shwepyitha', 'postal_code' => '11411'],
                ['name' => 'Mingaladon', 'postal_code' => '11021'],
                ['name' => 'Dala', 'postal_code' => '11321'],
                ['name' => 'Seikkyi Kanaungto', 'postal_code' => '11311'],
                ['name' => 'Twante', 'postal_code' => '11331'],
                ['name' => 'Kawhmu', 'postal_code' => '11341'],
                ['name' => 'Kungyangon', 'postal_code' => '11351'],
                ['name' => 'Hlegu', 'postal_code' => '11361'],
                ['name' => 'Hmawbi', 'postal_code' => '11371'],
                ['name' => 'Taikkyi', 'postal_code' => '11381'],
                ['name' => 'North Dagon', 'postal_code' => '11421'],
                ['name' => 'South Dagon', 'postal_code' => '11431'],
                ['name' => 'East Dagon', 'postal_code' => '11441'],
                ['name' => 'Dawbon', 'postal_code' => '11221'],
            ],
        ],
        [
            'name' => 'Mandalay',
            'delivery_fee' => 2500,
            'townships' => [
                ['name' => 'Aungmyethazan', 'postal_code' => '05011'],
                ['name' => 'Chanayethazan', 'postal_code' => '05021'],
                ['name' => 'Chanmyathazi', 'postal_code' => '05031'],
                ['name' => 'Mahaaungmye', 'postal_code' => '05041'],
                ['name' => 'Pyigyidagun', 'postal_code' => '05051'],
                ['name' => 'Amarapura', 'postal_code' => '05061'],
                ['name' => 'Patheingyi', 'postal_code' => '05071'],
                ['name' => 'Pyin Oo Lwin', 'postal_code' => '05081'],
                ['name' => 'Madaya', 'postal_code' => '05091'],
                ['name' => 'Singu', 'postal_code' => '05101'],
                ['name' => 'Myingyan', 'postal_code' => '05111'],
                ['name' => 'Taungtha', 'postal_code' => '05121'],
                ['name' => 'Natogyi', 'postal_code' => '05131'],
                ['name' => 'Kyaukpadaung', 'postal_code' => '05141'],
                ['name' => 'Nyaung-U', 'postal_code' => '05151'],
                ['name' => 'Mahlaing', 'postal_code' => '05161'],
                ['name' => 'Thazi', 'postal_code' => '05171'],
                ['name' => 'Wundwin', 'postal_code' => '05181'],
                ['name' => 'Meiktila', 'postal_code' => '05191'],
            ],
        ],
        [
            'name' => 'Naypyidaw',
            'delivery_fee' => 2500,
            'townships' => [
                ['name' => 'Ottarathiri', 'postal_code' => '15011'],
                ['name' => 'Dekkhinathiri', 'postal_code' => '15021'],
                ['name' => 'Pobbathiri', 'postal_code' => '15031'],
                ['name' => 'Zabuthiri', 'postal_code' => '15041'],
                ['name' => 'Zeyathiri', 'postal_code' => '15051'],
                ['name' => 'Pyinmana', 'postal_code' => '15061'],
                ['name' => 'Lewe', 'postal_code' => '15071'],
                ['name' => 'Tatkon', 'postal_code' => '15081'],
            ],
        ],
        [
            'name' => 'Bago',
            'delivery_fee' => 3000,
            'townships' => [
                ['name' => 'Bago', 'postal_code' => '06011'],
                ['name' => 'Daik-U', 'postal_code' => '06021'],
                ['name' => 'Kawa', 'postal_code' => '06031'],
                ['name' => 'Nyaunglebin', 'postal_code' => '06041'],
                ['name' => 'Shwegyin', 'postal_code' => '06051'],
                ['name' => 'Thanatpin', 'postal_code' => '06061'],
                ['name' => 'Wav', 'postal_code' => '06071'],
                ['name' => 'Kyauktaga', 'postal_code' => '06081'],
                ['name' => 'Taungoo', 'postal_code' => '06091'],
                ['name' => 'Pyay', 'postal_code' => '06101'],
                ['name' => 'Paukkaung', 'postal_code' => '06111'],
                ['name' => 'Thegon', 'postal_code' => '06121'],
                ['name' => 'Shwedaung', 'postal_code' => '06131'],
                ['name' => 'Paungde', 'postal_code' => '06141'],
                ['name' => 'Nattalin', 'postal_code' => '06151'],
                ['name' => 'Zigon', 'postal_code' => '06161'],
                ['name' => 'Okpho', 'postal_code' => '06171'],
                ['name' => 'Thayarwady', 'postal_code' => '06181'],
                ['name' => 'Letpadan', 'postal_code' => '06191'],
                ['name' => 'Minhla', 'postal_code' => '06201'],
                ['name' => 'Monyo', 'postal_code' => '06211'],
                ['name' => 'Oktwin', 'postal_code' => '06221'],
                ['name' => 'Gyobingauk', 'postal_code' => '06231'],
            ],
        ],
        [
            'name' => 'Magway',
            'delivery_fee' => 3500,
            'townships' => [
                ['name' => 'Magway', 'postal_code' => '03011'],
                ['name' => 'Minbu', 'postal_code' => '03021'],
                ['name' => 'Thayet', 'postal_code' => '03031'],
                ['name' => 'Pakokku', 'postal_code' => '03041'],
                ['name' => 'Aunglan', 'postal_code' => '03051'],
                ['name' => 'Natmauk', 'postal_code' => '03061'],
                ['name' => 'Taungdwingyi', 'postal_code' => '03071'],
                ['name' => 'Yenangyaung', 'postal_code' => '03081'],
                ['name' => 'Chauk', 'postal_code' => '03091'],
                ['name' => 'Gangaw', 'postal_code' => '03101'],
                ['name' => 'Saw', 'postal_code' => '03111'],
                ['name' => 'Pwinbyu', 'postal_code' => '03121'],
                ['name' => 'Salin', 'postal_code' => '03131'],
                ['name' => 'Sidoktaya', 'postal_code' => '03141'],
                ['name' => 'Myaing', 'postal_code' => '03151'],
                ['name' => 'Yesagyo', 'postal_code' => '03161'],
            ],
        ],
        [
            'name' => 'Sagaing',
            'delivery_fee' => 3000,
            'townships' => [
                ['name' => 'Sagaing', 'postal_code' => '01011'],
                ['name' => 'Monywa', 'postal_code' => '01021'],
                ['name' => 'Shwebo', 'postal_code' => '01031'],
                ['name' => 'Kanbalu', 'postal_code' => '01041'],
                ['name' => 'Kyunhla', 'postal_code' => '01051'],
                ['name' => 'Tamu', 'postal_code' => '01061'],
                ['name' => 'Kale', 'postal_code' => '01071'],
                ['name' => 'Kalewa', 'postal_code' => '01081'],
                ['name' => 'Mingin', 'postal_code' => '01091'],
                ['name' => 'Ye-U', 'postal_code' => '01101'],
                ['name' => 'Tabayin', 'postal_code' => '01111'],
                ['name' => 'Khin-U', 'postal_code' => '01121'],
                ['name' => 'Wetlet', 'postal_code' => '01131'],
                ['name' => 'Ayadaw', 'postal_code' => '01141'],
                ['name' => 'Budalin', 'postal_code' => '01151'],
                ['name' => 'Chaung-U', 'postal_code' => '01161'],
                ['name' => 'Myinmu', 'postal_code' => '01171'],
                ['name' => 'Pale', 'postal_code' => '01181'],
                ['name' => 'Salingyi', 'postal_code' => '01191'],
                ['name' => 'Yinmabin', 'postal_code' => '01201'],
                ['name' => 'Kani', 'postal_code' => '01211'],
                ['name' => 'Lahe', 'postal_code' => '01221'],
                ['name' => 'Nanyun', 'postal_code' => '01231'],
                ['name' => 'Hkamti', 'postal_code' => '01241'],
                ['name' => 'Homalin', 'postal_code' => '01251'],
                ['name' => 'Mawlaik', 'postal_code' => '01261'],
                ['name' => 'Phaungpyin', 'postal_code' => '01271'],
                ['name' => 'Pinlebu', 'postal_code' => '01281'],
                ['name' => 'Kawlin', 'postal_code' => '01291'],
                ['name' => 'Wuntho', 'postal_code' => '01301'],
                ['name' => 'Indaw', 'postal_code' => '01311'],
                ['name' => 'Katha', 'postal_code' => '01321'],
                ['name' => 'Tigyaing', 'postal_code' => '01331'],
                ['name' => 'Banmauk', 'postal_code' => '01341'],
                ['name' => 'Mohnyin', 'postal_code' => '01351'],
                ['name' => 'Mogaung', 'postal_code' => '01361'],
                ['name' => 'Myitkyina', 'postal_code' => '01371'],
                ['name' => 'Waingmaw', 'postal_code' => '01381'],
                ['name' => 'Hpakant', 'postal_code' => '01391'],
                ['name' => 'Tanai', 'postal_code' => '01401'],
                ['name' => 'Chipwi', 'postal_code' => '01411'],
                ['name' => 'Tsawlaw', 'postal_code' => '01421'],
                ['name' => 'Bhamo', 'postal_code' => '01431'],
                ['name' => 'Mansi', 'postal_code' => '01441'],
                ['name' => 'Momauk', 'postal_code' => '01451'],
                ['name' => 'Shwegu', 'postal_code' => '01461'],
            ],
        ],
        [
            'name' => 'Shan',
            'delivery_fee' => 4000,
            'townships' => [
                ['name' => 'Taunggyi', 'postal_code' => '07011'],
                ['name' => 'Kalaw', 'postal_code' => '07021'],
                ['name' => 'Nyaungshwe', 'postal_code' => '07031'],
                ['name' => 'Hopong', 'postal_code' => '07041'],
                ['name' => 'Hsihseng', 'postal_code' => '07051'],
                ['name' => 'Yaksawk', 'postal_code' => '07061'],
                ['name' => 'Pinlaung', 'postal_code' => '07071'],
                ['name' => 'Pekon', 'postal_code' => '07081'],
                ['name' => 'Lawksawk', 'postal_code' => '07091'],
                ['name' => 'Lashio', 'postal_code' => '07101'],
                ['name' => 'Kunlong', 'postal_code' => '07111'],
                ['name' => 'Tantyan', 'postal_code' => '07121'],
                ['name' => 'Hseni', 'postal_code' => '07131'],
                ['name' => 'Mongyai', 'postal_code' => '07141'],
                ['name' => 'Theinni', 'postal_code' => '07151'],
                ['name' => 'Muse', 'postal_code' => '07161'],
                ['name' => 'Kengtung', 'postal_code' => '07171'],
                ['name' => 'Tachileik', 'postal_code' => '07181'],
                ['name' => 'Mong Hsat', 'postal_code' => '07191'],
                ['name' => 'Mong Ping', 'postal_code' => '07201'],
                ['name' => 'Mong Ton', 'postal_code' => '07211'],
                ['name' => 'Mong Hpayak', 'postal_code' => '07221'],
                ['name' => 'Mong Yang', 'postal_code' => '07231'],
                ['name' => 'Langkho', 'postal_code' => '07241'],
                ['name' => 'Mawkmai', 'postal_code' => '07251'],
                ['name' => 'Mong Nai', 'postal_code' => '07261'],
                ['name' => 'Loilen', 'postal_code' => '07271'],
                ['name' => 'Lai-Hka', 'postal_code' => '07281'],
                ['name' => 'Nansang', 'postal_code' => '07291'],
                ['name' => 'Kyethi', 'postal_code' => '07301'],
                ['name' => 'Kunhing', 'postal_code' => '07311'],
                ['name' => 'Mong Kung', 'postal_code' => '07321'],
                ['name' => 'Hsipaw', 'postal_code' => '07331'],
                ['name' => 'Kyaukme', 'postal_code' => '07341'],
                ['name' => 'Namtu', 'postal_code' => '07351'],
                ['name' => 'Namhsan', 'postal_code' => '07361'],
                ['name' => 'Manton', 'postal_code' => '07371'],
                ['name' => 'Mongmit', 'postal_code' => '07381'],
                ['name' => 'Mabein', 'postal_code' => '07391'],
                ['name' => 'Panglong', 'postal_code' => '07401'],
            ],
        ],
        [
            'name' => 'Ayeyarwady',
            'delivery_fee' => 3500,
            'townships' => [
                ['name' => 'Pathein', 'postal_code' => '04011'],
                ['name' => 'Kangyidaunt', 'postal_code' => '04021'],
                ['name' => 'Ngapudaw', 'postal_code' => '04031'],
                ['name' => 'Kyaunggon', 'postal_code' => '04041'],
                ['name' => 'Thabaung', 'postal_code' => '04051'],
                ['name' => 'Einme', 'postal_code' => '04061'],
                ['name' => 'Wakema', 'postal_code' => '04071'],
                ['name' => 'Myaungmya', 'postal_code' => '04081'],
                ['name' => 'Labutta', 'postal_code' => '04091'],
                ['name' => 'Mawlamyinegyun', 'postal_code' => '04101'],
                ['name' => 'Pyapon', 'postal_code' => '04111'],
                ['name' => 'Bogale', 'postal_code' => '04121'],
                ['name' => 'Dedaye', 'postal_code' => '04131'],
                ['name' => 'Kyaiklat', 'postal_code' => '04141'],
                ['name' => 'Maubin', 'postal_code' => '04151'],
                ['name' => 'Nyaungdon', 'postal_code' => '04161'],
                ['name' => 'Danubyu', 'postal_code' => '04171'],
                ['name' => 'Hinthada', 'postal_code' => '04181'],
                ['name' => 'Zalun', 'postal_code' => '04191'],
                ['name' => 'Lemyethna', 'postal_code' => '04201'],
                ['name' => 'Yegyi', 'postal_code' => '04211'],
            ],
        ],
        [
            'name' => 'Tanintharyi',
            'delivery_fee' => 4500,
            'townships' => [
                ['name' => 'Dawei', 'postal_code' => '14011'],
                ['name' => 'Launglon', 'postal_code' => '14021'],
                ['name' => 'Thayetchaung', 'postal_code' => '14031'],
                ['name' => 'Yebyu', 'postal_code' => '14041'],
                ['name' => 'Myitta', 'postal_code' => '14051'],
                ['name' => 'Palaw', 'postal_code' => '14061'],
                ['name' => 'Myeik', 'postal_code' => '14071'],
                ['name' => 'Kyunsu', 'postal_code' => '14081'],
                ['name' => 'Tanintharyi', 'postal_code' => '14091'],
                ['name' => 'Kawthoung', 'postal_code' => '14101'],
                ['name' => 'Bokpyin', 'postal_code' => '14111'],
                ['name' => 'Khamaukgyi', 'postal_code' => '14121'],
            ],
        ],
        [
            'name' => 'Mon',
            'delivery_fee' => 3500,
            'townships' => [
                ['name' => 'Mawlamyine', 'postal_code' => '12011'],
                ['name' => 'Chaungzon', 'postal_code' => '12021'],
                ['name' => 'Kyaikmaraw', 'postal_code' => '12031'],
                ['name' => 'Kyaikmayaw', 'postal_code' => '12041'],
                ['name' => 'Mudon', 'postal_code' => '12051'],
                ['name' => 'Thanbyuzayat', 'postal_code' => '12061'],
                ['name' => 'Ye', 'postal_code' => '12071'],
                ['name' => 'Thaton', 'postal_code' => '12081'],
                ['name' => 'Paung', 'postal_code' => '12091'],
                ['name' => 'Bilin', 'postal_code' => '12101'],
                ['name' => 'Kyaikto', 'postal_code' => '12111'],
            ],
        ],
        [
            'name' => 'Kayin',
            'delivery_fee' => 3500,
            'townships' => [
                ['name' => 'Hpa-An', 'postal_code' => '13011'],
                ['name' => 'Hlaingbwe', 'postal_code' => '13021'],
                ['name' => 'Paingkyon', 'postal_code' => '13031'],
                ['name' => 'Kyaikdon', 'postal_code' => '13041'],
                ['name' => 'Myawaddy', 'postal_code' => '13051'],
                ['name' => 'Kawkareik', 'postal_code' => '13061'],
                ['name' => 'Kyainseikgyi', 'postal_code' => '13071'],
            ],
        ],
        [
            'name' => 'Kayah',
            'delivery_fee' => 4000,
            'townships' => [
                ['name' => 'Loikaw', 'postal_code' => '11011'],
                ['name' => 'Demoso', 'postal_code' => '11021'],
                ['name' => 'Hpruso', 'postal_code' => '11031'],
                ['name' => 'Shadaw', 'postal_code' => '11041'],
                ['name' => 'Bawlakhe', 'postal_code' => '11051'],
                ['name' => 'Mese', 'postal_code' => '11061'],
            ],
        ],
        [
            'name' => 'Chin',
            'delivery_fee' => 5000,
            'townships' => [
                ['name' => 'Hakha', 'postal_code' => '02011'],
                ['name' => 'Thantlang', 'postal_code' => '02021'],
                ['name' => 'Falam', 'postal_code' => '02031'],
                ['name' => 'Tedim', 'postal_code' => '02041'],
                ['name' => 'Tonzang', 'postal_code' => '02051'],
                ['name' => 'Matupi', 'postal_code' => '02061'],
                ['name' => 'Paletwa', 'postal_code' => '02071'],
                ['name' => 'Mindat', 'postal_code' => '02081'],
                ['name' => 'Kanpetlet', 'postal_code' => '02091'],
            ],
        ],
        [
            'name' => 'Rakhine',
            'delivery_fee' => 4500,
            'townships' => [
                ['name' => 'Sittwe', 'postal_code' => '08011'],
                ['name' => 'Pauktaw', 'postal_code' => '08021'],
                ['name' => 'Ponnagyun', 'postal_code' => '08031'],
                ['name' => 'Mrauk-U', 'postal_code' => '08041'],
                ['name' => 'Kyauktaw', 'postal_code' => '08051'],
                ['name' => 'Minbya', 'postal_code' => '08061'],
                ['name' => 'Myebon', 'postal_code' => '08071'],
                ['name' => 'Ann', 'postal_code' => '08081'],
                ['name' => 'Ramree', 'postal_code' => '08091'],
                ['name' => 'Manaung', 'postal_code' => '08101'],
                ['name' => 'Thandwe', 'postal_code' => '08111'],
                ['name' => 'Toungup', 'postal_code' => '08121'],
                ['name' => 'Gwa', 'postal_code' => '08131'],
                ['name' => 'Maungdaw', 'postal_code' => '08141'],
                ['name' => 'Buthidaung', 'postal_code' => '08151'],
                ['name' => 'Rathedaung', 'postal_code' => '08161'],
                ['name' => 'Kyaukpyu', 'postal_code' => '08171'],
            ],
        ],
    ];

    public function run(): void
    {
        $tenants = Tenant::all();

        if ($tenants->isEmpty()) {
            $this->command->warn('No tenants found. Skipping location seeding.');
            return;
        }

        foreach ($tenants as $tenant) {
            foreach ($this->locations as $cityData) {
                $city = City::firstOrCreate(
                    ['tenant_id' => $tenant->id, 'name' => $cityData['name']],
                    [
                        'delivery_fee' => $cityData['delivery_fee'],
                        'is_active' => true,
                    ]
                );

                foreach ($cityData['townships'] as $townshipData) {
                    Township::firstOrCreate(
                        ['city_id' => $city->id, 'name' => $townshipData['name']],
                        [
                            'postal_code' => $townshipData['postal_code'],
                            'is_active' => true,
                        ]
                    );
                }
            }
        }

        $this->command->info('Default locations seeded successfully for all tenants.');
    }
}
