import { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { adminUrl } from '@/Utils/adminUrl';

export default function StorefrontCompare({ comparison, revisions = [] }) {
    const [from, setFrom] = useState(String(comparison?.from?.id || ''));
    const [to, setTo] = useState(String(comparison?.to?.id || ''));
    const compare = (event) => { event.preventDefault(); router.get(adminUrl('/admin/storefront/revisions/compare'), { from, to }, { preserveState: true, replace: true }); };
    return <AdminLayout><Head title="Compare Storefront Revisions" /><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6 lg:py-8"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="text-sm font-medium text-blue-600">Storefront</p><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mt-1">Compare Revisions</h1><p className="text-sm text-gray-500 mt-1">Review meaningful storefront changes before publishing.</p></div><Link href={adminUrl('/admin/storefront/revisions')} className="text-sm text-blue-600">Back to History</Link></div><form onSubmit={compare} className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4 flex flex-col sm:flex-row gap-3 items-end mb-6"><Select label="Previous" value={from} onChange={setFrom} revisions={revisions} /><Select label="Current" value={to} onChange={setTo} revisions={revisions} /><button className="px-4 py-2.5 rounded-lg bg-blue-600 text-white text-sm font-semibold">Compare</button></form><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-6"><Summary label="Previous" value={`Revision ${comparison?.from?.revision_number || '-'}`} /><Summary label="Current" value={`Revision ${comparison?.to?.revision_number || '-'}`} /></div><div className="space-y-4">{comparison?.changes?.map((group) => <section key={group.area} className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden"><h2 className="px-4 py-3 font-semibold text-gray-900 dark:text-gray-100 border-b border-gray-200 dark:border-gray-800">{group.area}</h2><div className="divide-y divide-gray-100 dark:divide-gray-800">{group.changes.map((change, index) => <div key={`${change.label}-${index}`} className="grid grid-cols-1 sm:grid-cols-[1fr_1fr_1fr] gap-2 px-4 py-3 text-sm"><span className="font-medium text-gray-700 dark:text-gray-300">{change.label}</span><span className="text-gray-500 dark:text-gray-400">{change.previous}</span><span className="text-gray-900 dark:text-gray-100">{change.current}</span></div>)}</div></section>)}{!comparison?.changes?.length && <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-10 text-center text-sm text-gray-500">No meaningful changes between these revisions.</div>}</div></div></AdminLayout>;
}

function Select({ label, value, onChange, revisions }) { return <label className="flex-1 w-full text-sm font-medium text-gray-700 dark:text-gray-300">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 font-normal">{revisions.map((revision) => <option key={revision.id} value={revision.id}>Revision {revision.revision_number} ({revision.status})</option>)}</select></label>; }
function Summary({ label, value }) { return <div className="rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-4"><p className="text-xs uppercase tracking-wide text-gray-500">{label}</p><p className="mt-1 font-semibold text-gray-900 dark:text-gray-100">{value}</p></div>; }
