import { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { adminUrl } from '@/Utils/adminUrl';

const labels = { hero: 'Hero', promotion: 'Promotions', featured_categories: 'Featured Categories', featured_products: 'Featured Products', product_showcase: 'Product Showcase', store_highlights: 'Store Highlights', brand_story: 'Brand Story', cta: 'Call to Action' };

export default function StorefrontHomepage({ sections: initialSections = [], categories = [], products = [], media = [], heroVariants = ['default', 'split', 'centered', 'text-only', 'minimal'] }) {
    const [sections, setSections] = useState(initialSections);
    const [saving, setSaving] = useState(false);
    const update = (id, changes) => setSections((current) => current.map((section) => section.id === id ? { ...section, ...changes } : section));
    const updateConfig = (id, changes) => setSections((current) => current.map((section) => section.id === id ? { ...section, configuration: { ...(section.configuration || {}), ...changes } } : section));
    const move = (index, direction) => { const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= sections.length) return; setSections((current) => { const next = [...current]; [next[index], next[nextIndex]] = [next[nextIndex], next[index]]; return next; }); };
    const save = (event) => { event.preventDefault(); setSaving(true); router.put(adminUrl('/admin/storefront/homepage'), { sections: sections.map((section, position) => ({ ...section, position })) }, { preserveScroll: true, onFinish: () => setSaving(false) }); };

    return <AdminLayout><Head title="Homepage Sections" /><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6 lg:py-8"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="text-sm font-medium text-blue-600">Storefront</p><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mt-1">Homepage Sections</h1><p className="text-sm text-gray-500 mt-1">Configure discovery and marketing sections. Empty sections stay hidden from customers.</p></div><Link href={adminUrl('/admin/storefront')} className="text-sm text-blue-600">Back to Storefront</Link></div><form onSubmit={save} className="space-y-4">{sections.map((section, index) => <section key={section.id} className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex-1"><h2 className="font-semibold text-gray-900 dark:text-gray-100">{labels[section.type] || section.type}</h2><p className="text-xs text-gray-500 mt-1">{description(section.type)}</p></div><Toggle label="Enabled" checked={section.enabled} onChange={(value) => update(section.id, { enabled: value })} /><button type="button" onClick={() => move(index, -1)} disabled={index === 0} className="px-2 py-1 rounded border text-xs disabled:opacity-30">Up</button><button type="button" onClick={() => move(index, 1)} disabled={index === sections.length - 1} className="px-2 py-1 rounded border text-xs disabled:opacity-30">Down</button></div><div className="flex flex-wrap items-end gap-4 mt-4"><Toggle label="Desktop" checked={section.desktop_visible} onChange={(value) => update(section.id, { desktop_visible: value })} /><Toggle label="Mobile" checked={section.mobile_visible} onChange={(value) => update(section.id, { mobile_visible: value })} /><VariantField value={section.variant || 'default'} options={variantOptions(section.type, heroVariants)} onChange={(value) => update(section.id, { variant: value })} /></div><SectionConfig section={section} categories={categories} products={products} media={media} updateConfig={updateConfig} /></section>)}</form><div className="flex justify-end mt-6"><button onClick={save} disabled={saving} className="px-5 py-2.5 rounded-lg bg-blue-600 text-white text-sm font-semibold disabled:opacity-50">{saving ? 'Saving...' : 'Save Homepage'}</button></div></div></AdminLayout>;
}

function SectionConfig({ section, categories, products, media, updateConfig }) {
    const config = section.configuration || {};
    if (section.type === 'hero') return <p className="mt-5 pt-4 border-t text-sm text-gray-500">Hero content is managed from the main Storefront Homepage tab. Media is managed in the Storefront Media Library.</p>;
    if (section.type === 'promotion') return <p className="mt-5 pt-4 border-t text-sm text-gray-500">Create and schedule promotions from <Link href={adminUrl('/admin/storefront/promotions')} className="text-blue-600">Promotions & Campaigns</Link>.</p>;
    if (section.type === 'featured_categories') return <SelectionList title="Categories" items={categories} selected={config.category_ids || []} onChange={(ids) => updateConfig(section.id, { category_ids: ids, limit: config.limit || 6 })} />;
    if (section.type === 'featured_products' || section.type === 'product_showcase') return <div className="mt-5 pt-4 border-t space-y-4"><Field label="Section title" value={config.title || ''} onChange={(value) => updateConfig(section.id, { title: value })} /><Field label="Description" value={config.description || ''} onChange={(value) => updateConfig(section.id, { description: value })} /><SelectionList title="Products" items={products} selected={config.product_ids || []} onChange={(ids) => updateConfig(section.id, { product_ids: ids, limit: config.limit || 8 })} /></div>;
    if (section.type === 'store_highlights') return <Highlights items={config.items || []} onChange={(items) => updateConfig(section.id, { items })} />;
    if (section.type === 'brand_story') return <div className="mt-5 pt-4 border-t grid grid-cols-1 sm:grid-cols-2 gap-4"><p className="sm:col-span-2 text-sm text-gray-500">Brand Story content comes from Website Settings → About Us. This section controls presentation, visibility, optional media, and the CTA.</p><Field label="Button label" value={config.button_text || ''} onChange={(value) => updateConfig(section.id, { button_text: value })} /><Field label="Button link" value={config.button_link || ''} onChange={(value) => updateConfig(section.id, { button_link: value })} /><MediaSelect config={config} media={media} onChange={(media_id) => updateConfig(section.id, { media_id })} /></div>;
    if (section.type === 'cta') return <div className="mt-5 pt-4 border-t grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Title" value={config.title || ''} onChange={(value) => updateConfig(section.id, { title: value })} /><Field label="Button label" value={config.button_text || ''} onChange={(value) => updateConfig(section.id, { button_text: value })} /><Field label="Description" value={config.description || ''} onChange={(value) => updateConfig(section.id, { description: value })} /><Field label="Button link" value={config.button_link || ''} onChange={(value) => updateConfig(section.id, { button_link: value })} /><MediaSelect config={config} media={media} onChange={(media_id) => updateConfig(section.id, { media_id })} /></div>;
    return null;
}

function SelectionList({ title, items, selected, onChange }) { const values = selected.map(Number); const toggle = (id) => onChange(values.includes(Number(id)) ? values.filter((value) => value !== Number(id)) : [...values, Number(id)]); return <div className="mt-5 pt-4 border-t"><p className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">{title}</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 max-h-56 overflow-y-auto">{items.map((item) => <label key={item.id} className="flex items-center gap-2 rounded border border-gray-200 dark:border-gray-700 p-2 text-sm text-gray-600 dark:text-gray-300"><input type="checkbox" checked={values.includes(Number(item.id))} onChange={() => toggle(item.id)} className="rounded border-gray-300 text-blue-600" />{item.name}</label>)}</div></div>; }
function Highlights({ items, onChange }) { const update = (index, key, value) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)); const add = () => onChange([...items, { icon: 'star', title: '', description: '' }]); return <div className="mt-5 pt-4 border-t space-y-3">{items.map((item, index) => <div key={index} className="grid grid-cols-1 sm:grid-cols-3 gap-2"><select value={item.icon || 'star'} onChange={(event) => update(index, 'icon', event.target.value)} className="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 text-sm"><option value="star">Star</option><option value="truck">Delivery</option><option value="shield">Secure</option><option value="headset">Support</option><option value="heart">Care</option></select><input value={item.title || ''} onChange={(event) => update(index, 'title', event.target.value)} placeholder="Title" className="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 text-sm" /><input value={item.description || ''} onChange={(event) => update(index, 'description', event.target.value)} placeholder="Description" className="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 text-sm" /></div>)}<button type="button" onClick={add} disabled={items.length >= 6} className="text-sm text-blue-600 disabled:opacity-40">+ Add highlight</button></div>; }
function Field({ label, value, onChange }) { return <label className="text-sm font-medium text-gray-700 dark:text-gray-300">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 font-normal" /></label>; }
function MediaSelect({ config, media, onChange }) { return <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Optional image<select value={config.media_id || ''} onChange={(event) => onChange(event.target.value || null)} className="mt-1 w-full rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 font-normal"><option value="">No image</option>{media.map((item) => <option key={item.id} value={item.id}>{item.alt_text || `Media #${item.id}`}</option>)}</select></label>; }
function Toggle({ label, checked, onChange }) { return <label className="inline-flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="rounded border-gray-300 text-blue-600" />{label}</label>; }
function VariantField({ value, options, onChange }) { return <label className="text-xs font-medium text-gray-600 dark:text-gray-300">Layout<select value={value} onChange={(event) => onChange(event.target.value)} className="block mt-1 rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 text-sm"><option value="default">Theme default</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
function variantOptions(type, heroVariants = []) { return { hero: heroVariants, featured_categories: ['default', 'grid', 'horizontal', 'compact'], featured_products: ['default', 'grid', 'compact', 'image-focused', 'horizontal'], product_showcase: ['default', 'grid', 'compact', 'image-focused', 'horizontal'], brand_story: ['default', 'split', 'text-only'], cta: ['default', 'centered', 'full-width'] }[type] || []; }
function description(type) { return { promotion: 'Display active scheduled campaigns.', featured_categories: 'Help customers discover collections.', featured_products: 'Show selected products near the top of the store.', product_showcase: 'Present a selected product group.', store_highlights: 'Explain why customers should shop with you.', brand_story: 'Tell your store story with an optional image.', cta: 'End the page with a clear next action.' }[type] || 'Configure this homepage section.'; }
