import { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { adminUrl } from '@/Utils/adminUrl';

export default function StorefrontRevisions({ revisions, publishedRevisionId, draftRevisionId }) {
    const [from, setFrom] = useState(String(revisions.data?.[1]?.id || revisions.data?.[0]?.id || ''));
    const [to, setTo] = useState(String(revisions.data?.[0]?.id || ''));
    const compareUrl = `${adminUrl('/admin/storefront/revisions/compare')}?from=${from}&to=${to}`;
    const restore = (revision) => { if (window.confirm('Restore this revision as a draft? The live storefront will not change until you publish it.')) router.post(adminUrl(`/admin/storefront/revisions/${revision.id}/restore`), {}, { preserveScroll: true }); };
    return <AdminLayout><Head title="Storefront Revision History" /><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 lg:py-8"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="text-sm font-medium text-blue-600">Storefront</p><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mt-1">Revision History</h1><p className="text-sm text-gray-500 mt-1">Restore a previous version as a draft, then preview and publish it.</p></div><Link href={adminUrl('/admin/storefront')} className="text-sm text-blue-600">Back to Storefront</Link></div><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4 mb-4 flex flex-col sm:flex-row gap-3 items-end"><Select label="Previous" value={from} onChange={setFrom} revisions={revisions.data || []} /><Select label="Current" value={to} onChange={setTo} revisions={revisions.data || []} /><a href={compareUrl} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-semibold">Compare</a></div><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 divide-y divide-gray-200 dark:divide-gray-800">{revisions.data?.map((revision) => <div key={revision.id} className="p-4 flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex-1"><p className="font-semibold text-gray-900 dark:text-gray-100">Revision {revision.revision_number}</p><p className="text-xs text-gray-500 mt-1">Created {formatDate(revision.created_at)} by {revision.created_by}{revision.published_at ? ` · Published ${formatDate(revision.published_at)} by ${revision.published_by || 'System'}` : ''}</p></div><div className="flex items-center gap-2"><Status status={revision.status} isDraft={revision.id === draftRevisionId} isPublished={revision.id === publishedRevisionId} />{revision.id !== publishedRevisionId && <button type="button" onClick={() => restore(revision)} className="px-3 py-1.5 rounded border text-xs">Restore as Draft</button>}</div></div>)}{!revisions.data?.length && <p className="p-8 text-center text-sm text-gray-500">No revisions yet. Save a storefront change to create a draft.</p>}</div></div></AdminLayout>;
}

function formatDate(value) { return value ? new Date(value).toLocaleString() : 'unknown date'; }
function Select({ label, value, onChange, revisions }) { return <label className="flex-1 w-full text-sm font-medium text-gray-700 dark:text-gray-300">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-800 font-normal">{revisions.map((revision) => <option key={revision.id} value={revision.id}>Revision {revision.revision_number}</option>)}</select></label>; }
function Status({ status, isDraft, isPublished }) { if (isDraft) return <span className="px-2 py-1 rounded-full bg-amber-100 text-amber-700 text-xs">Draft</span>; if (isPublished) return <span className="px-2 py-1 rounded-full bg-green-100 text-green-700 text-xs">Published</span>; return <span className="px-2 py-1 rounded-full bg-gray-100 text-gray-600 text-xs">{status === 'archived' ? 'Archived' : status}</span>; }
